### ISSUE TITLE
Two iota

### ISSUE THREAD

**Issue by stati64** [powturbo/Turbo-Range-Coder#1]
TRC is lovely. 

1. these encoders can write past end of buffer.  Is there a maximum over-run?

2. This seems to fix over runs:
#define OVERFLOW(_in_, _inlen_) if(op >= out+_inlen_-16) { memcpy(out, _in_, _inlen_); return _inlen_; }

3. It seems cleaner to specify the outlen as a parameter (inlen for decompress).
outlen might be reduced externally for application reasons and internally for maximum overrun.
Omitting the memcpy()
#define OVERFLOW(_in_, _inlen_) if(op >= outbound)return 0;

Thanks!

**Comment by powturbo** [comment]
Thank you.

> these encoders can write past end of buffer. Is there a maximum over-run?

With the recent changes, the output buffer length must be at least equal to the 
input buffer length inlen. 
If the input is nearly incompressible, inlen is returned to the caller and the input is copied to the output.

```
Encoding :
out = malloc(inlen);
outlen = rcsenc(in, inlen, out);
```
```
Decoding: 
if (inlen == outlen) memcpy(out, in, outlen);
else rcsdec(in, outlen, out);

``` 

> It seems cleaner to specify the outlen as a parameter (inlen for decompress).

The outlen (output size) in compression is not needed, the output buffer must be a least equal 
to the input buffer length.
The encoded length inlen is also not needed  in decompression.
Only outlen bytes are decoded, so partial decoding is possible.
This has also the advantage to only store the last block length, when you're compressing
large files with small blocks.
See "turborc.c"

TurboRC is as simple to use as a memcpy.

The functions in turborcs and turborcss are provided as templates to show how to use TurboRC.
Depending on your use case, you can write your own functions with your own 
predictors.
