### ISSUE TITLE
Level 25 fails decompression on enwik8

### ISSUE THREAD

**Issue by flanglet** [powturbo/Turbo-Range-Coder#2]
./turborc -25 /tmp/enwik8 /tmp/enwik8.rc
ll /tmp/enwik8.rc
-rw-rw-r-- 1 fred fred 58290080 Mar 21 13:03 /tmp/enwik8.rc
rm /tmp/enwik8.rc.bak
./turborc -d /tmp/enwik8.rc /tmp/enwik8.rc.bak
ll /tmp/enwik8.rc.bak
-rw-rw-r-- 1 fred fred 100000000 Mar 21 13:04 /tmp/enwik8.rc.bak
md5sum /tmp/enwik8.rc.bak /tmp/enwik8
0f86d7c5a6180cf9584c1d21144d85b0  /tmp/enwik8.rc.bak
a1fa5ffddb56f4953e226637dabbb36a  /tmp/enwik8

**Comment by powturbo** [comment]
Thanks for reporting. Should be fixed now.
25 is more interesting for bwt data.

**Comment by flanglet** [comment]
Fix confirmed. That was quick !
