### ISSUE TITLE
Support for Android? Source code for range coder order 0?

### ISSUE THREAD

**Issue by hujinhan12** [powturbo/Turbo-Range-Coder#3]
Hi,
I have two questions.
1) Is there any plan to support building in Android NDK?
2) If not, can you please point to me the source code to implement range coder order 0 from scratch?
Please let me know, thank you.

**Comment by powturbo** [comment]
I don't see any obstacle to build turborc on Android with the provided makefile.

**Comment by hujinhan12** [comment]
Thank you for the response.

Please let me know how to compile turborc for Android aarch64 on a linux machine. Really appreciate it.

**Comment by powturbo** [comment]
You must first learn how to  build c-programs under Android NDK and using make.
You can then clone "Turbo-Range-Coder" and build it using the provided makefile.
