### ISSUE TITLE
Issues compiling for arm64 macOS

### ISSUE THREAD

**Issue by michaeleisel** [powturbo/Turbo-Range-Coder#5]
I'm trying to compile it for my machine and having some issues:
- Some per-source file flags in the makefile seem tied to Intel:
```
 $(L)anscdfs.o: $(L)anscdf.c $(L)anscdf_.h
-       $(CC) -c -O3 $(CFLAGS) -march=corei7-avx -mtune=corei7-avx -mno-aes -falign-loops=32 $(L)anscdf.c -o $(L)anscdfs.o  
+       $(CC) -c -O3 $(CFLAGS) -mno-aes -falign-loops=32 $(L)anscdf.c -o $(L)anscdfs.o  
 
 $(L)anscdfx.o: $(L)anscdf.c $(L)anscdf_.h
-       $(CC) -c -O3 $(CFLAGS) -march=haswell -falign-loops=32 $(L)anscdf.c -o $(L)anscdfx.o 
+       $(CC) -c -O3 $(CFLAGS) -falign-loops=32 $(L)anscdf.c -o $(L)anscdfx.o 
```
- Architecture detection seems to look for aarch64 but not arm64, which is what the machine returns for `uname -s`
- Frame pointers shouldn't be omitted for any macOS binaries
- There are many system headers that needed to be included to different files, or else add `CFLAGS+=-Wno-implicit-function-declaration`
- Issue with `sse_neon.h`:
```
./include_/sse_neon.h:232:85: error: invalid conversion between vector type 'uint64x2_t' (vector of 2 'uint64_t' values) and 'uint8x8_t' (vector of 8 'uint8_t' values) of different size
static ALWAYS_INLINE uint64_t  mm_movemask4_epu8(__m128i v) { return vgetq_lane_u64((uint64x2_t)vshrn_n_u16((uint8x16_t)v, 4), 0); } //uint8x16_t
```
- Issue of using `__m128i` for arm64:
```
./include_/bitutil_.h:128:77: error: returning 'int' from a function with incompatible result type 'uint32x4_t' (vector of 4 'uint32_t' values)
static ALWAYS_INLINE __m128i mm_delta_epi64(__m128i v, __m128i sv) { return _mm_sub_epi64(v, _mm_alignr_epi8(v, sv,  8)); }
```
e.g. here:
```
  #if defined(__SSSE3__) || defined(__ARM_NEON)
#define mm_srai_epi64_63(_v_, _s_) _mm_srai_epi32(_mm_shuffle_epi32(_v_, _MM_SHUFFLE(3, 3, 1, 1)), 31)
  
static ALWAYS_INLINE __m128i mm_zzage_epi16(__m128i v) { return _mm_xor_si128( mm_slli_epi16(v,1),  mm_srai_epi16(   v,15)); }
```

Those last couple issues are the main ones preventing me from compiling it, the other ones were easy to patch

**Comment by powturbo** [comment]
I've updated the files sse_neon, bitutil_.h from the current TurboPFor
which I konw it's compiling on M1 without issues. I've also changed the makefile to consider arm64.
Can you compiling try now.

I've added a new 8 bits quantization, I'll publish the results on encode.su

**Comment by michaeleisel** [comment]
Hi, did you update it on master? I'm still getting the same issues, and I'm seeing the last update to sse_neon.h in May:
```
$ git log -- ./include_/sse_neon.h
commit 2e3f0732b2976d4744861d132a172d835a572d4f
Author: x <powturbo@gmail.com>
Date:   Thu Mar 23 20:28:58 2023 +0100

    TurboRC: c/c++ header
~/projects/Turbo-Range-Coder on master
$ git pull
Already up to date.
```

**Comment by powturbo** [comment]
sorry, not all files where updated. Can you try again now.?

Results are [published at encode.su](https://encode.su/threads/4067-Good-Compressors-for-16-bit-floats?p=79850#post79850)

**Comment by michaeleisel** [comment]
Thanks for the changes, I think it is closer. I now see the following issues:
- Many C stdlib functions that don't have the necessary includes (resolved with `CFLAGS+=-Wno-implicit-function-declaration` in the Makefile)
- The flags `-march=corei7-avx` and `-march=haswell` (resolved by just removing them)
- Linker errors:
```
Undefined symbols for architecture arm64:
  "_ansbc", referenced from:
      _bench in turborc.o
  "_ansbd", referenced from:
      _bench in turborc.o
  "_anscdf1dec", referenced from:
      _bench in turborc.o
     (maybe you meant: _anscdf1decs)
  "_anscdf1enc", referenced from:
      _bench in turborc.o
     (maybe you meant: _anscdf1encs)
  "_anscdf4dec", referenced from:
  ...
  ```
  - After commenting out the `bench` function (instead of using `-DNO_BENCH` since that caused other issues), I still get:
  ```
  Undefined symbols for architecture arm64:
  "_anscdfini", referenced from:
      _anscdf4sencs in anscdfx.o
      _anscdf4sdecs in anscdfx.o
      _anscdf4decs in anscdfx.o
      _anscdf4encs in anscdfx.o
      _anscdfuenc16s in anscdfx.o
      _anscdfudec16s in anscdfx.o
      _anscdfuzenc16s in anscdfx.o
```

**Comment by powturbo** [comment]
I've reworked the whole makefile, because of SIMD it's more complicated than just enabling/disabling some switches.
I've cross compiled TurboRC for am64 on linux without any issue.
Can you please try again?

**Comment by michaeleisel** [comment]
I'm still getting linker errors:
```
Undefined symbols for architecture arm64:
  "_anscdf1decx", referenced from:
      _anscdf4sencs in anscdfs.o
      _anscdfini in anscdfs.o
      _anscdf4sdecs in anscdfs.o
      _anscdf4decs in anscdfs.o
      _anscdf4encs in anscdfs.o
      _anscdfuenc16s in anscdfs.o
      _anscdfudec16s in anscdfs.o
      ...
  "_anscdf1encx", referenced from:
      _anscdf4sencs in anscdfs.o
      _anscdfini in anscdfs.o
      _anscdf4sdecs in anscdfs.o
      _anscdf4decs in anscdfs.o
```

**Comment by powturbo** [comment]
can you please post the whole compiler output here ?  don't forget "make clean" before "make"
The functions with x suffix are avx2 and not included here on arm64.
Try to change this [line](https://github.com/powturbo/Turbo-Range-Coder/blob/fbac14bf2109ae3697bcff1cd407671c9fdea8af/anscdf.c#L766) to "#if 0"

**Comment by michaeleisel** [comment]
I think the issue is incorrect architecture detection. `uname -m` returns `arm64`, not `aarch64`. In general, I think it may be tough to fully test this on an arm64 Linux machine. I did get it to build though, by adding `CFLAGS+=-D_NAVX2 -D_NSCALAR` outside of the architecture if statements. Here are my results, which seem not to match those you posted in the forum. Here, `all.f16` is the file that was uploaded to Google Drive:
```
$ ../Turbo-Range-Coder/turborc -24 all.f16 all -q8 -v5
'all.f16'
no codec
bsize=1879048192 read=1719042048 line=1079 ~/projects/floaty on main*

$ ../Turbo-Range-Coder/turborc -e11,56,64 all.rc
      size   ratio     E MB/s   D MB/s function prdid='s(5)'
        10 100.00%       4.00  4579.22 11:rcmr      o2 8b mixer/sse run         	all.rc
        10 100.00%     109.16  4578.43 56:ans auto                              	all.rc
        10 100.00%       3.23  4596.50 64:ans auto  o1                          	all.rc
Best methods =64,56,11

$ ../Turbo-Range-Coder/turborc -e86 all.f16 -q8 -v5
BENCHMARK ARGS: fno=0,optind=4,argc=5
      size   ratio     E MB/s   D MB/s function prdid='s(5)'
'all.f16'
bsize=1879048192 b=1719042048 read=1719042048

$ ../Turbo-Range-Coder/turborc -e87 all.f16 -Z.1 -v5
BENCHMARK ARGS: fno=0,optind=4,argc=5
      size   ratio     E MB/s   D MB/s function prdid='s(5)'
'all.f16'
bsize=1879048192 b=1719042048 read=1719042048
```

**Comment by powturbo** [comment]
The arch is detected from the OS (uname -m) and compiler string CC, which works with cross-compling. 

It seems _Float16 is not supported or not detected (see turborc.c & rcutil.c) on your plattform.
You see 'no codec' which means the quantization codec "-24" is not available. The input is simply stored into the output.

1 - Check, if _Float type is supported
2 - If, Yes then figure out how the activate it. Normally by checking FLT16_MAX (from "float.h") as in rcutil.c

can you post the output of "uname -m"?
what's the compiler you are using? pls, post the output of "cc -v"

**Comment by michaeleisel** [comment]
```
$ uname -m
arm64

$ cc -v
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Applications/Xcode-14.3.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by michaeleisel** [comment]
clang is essentially the standard on macOS because of it being shipped (and not GCC) in the Xcode toolchain

**Comment by powturbo** [comment]
ok, the arch must be correctly detected now (from the [uname -m = arm64](https://github.com/powturbo/Turbo-Range-Coder/blob/3397d30542e650154996119907c2b74dec29c9d8/makefile#L54) ).
Can you try again ?
clang is normally supporting the _Float16 type. see the [detection](https://github.com/powturbo/Turbo-Range-Coder/blob/3397d30542e650154996119907c2b74dec29c9d8/include_/conf.h#L41)

**Comment by michaeleisel** [comment]
It still doesn't work on `master`, but I was able to get it to work with the following patch:
```
diff --git a/include_/conf.h b/include_/conf.h
index f16fc60..18f74a9 100755
--- a/include_/conf.h
+++ b/include_/conf.h
@@ -45,6 +45,7 @@ typedef unsigned long long uint64_t;
 #elif defined(FLT16_MAX)
 #define FLT16_BUILTIN
 #endif
+#define FLT16_BUILTIN
 
 //------------------------- Compiler ------------------------------------------
   #if defined(__GNUC__)
diff --git a/include_/rcutil.h b/include_/rcutil.h
index 160e3b6..212c74b 100755
--- a/include_/rcutil.h
+++ b/include_/rcutil.h
@@ -59,6 +59,7 @@ void      delta8d24(uint8_t *in, size_t n, uint8_t *out);
 #elif defined(FLT16_MAX)
 #define FLT16_BUILTIN
 #endif
+#define FLT16_BUILTIN
 //------- Quantization [0..qmax] : qmax maximum quantized value in out ----------------
   #if defined(FLT16_BUILTIN) 
 size_t fpquant8e16( _Float16 *in, size_t inlen, uint8_t  *out, unsigned qmax, _Float16 *pfmin, _Float16 *pfmax, _Float16 zmin);
diff --git a/makefile b/makefile
index e2d8469..c54adb2 100755
--- a/makefile
+++ b/makefile
@@ -213,6 +213,7 @@ ifeq ($(NOCOMP), 1)
 CFLAGS+=-DNO_COMP
 endif
 
+CFLAGS+=-Wno-implicit-function-declaration
 
 #librc.a: $(LIB)
 #      ar cr $@ $+
```

anyways, once it's built, i see the following:
```
$ ../Turbo-Range-Coder/turborc -24 all.f16 all -q8 -v5
'all.f16'
bsize=1879048192 read=1719042048 qmax=254 outliers:598+514=1112 
len:859523253 R:[-1.16016/1.40039]=2.56055 q=8 compress: 'all.f16'  1719042048->859523271

$ ../Turbo-Range-Coder/turborc -e11,56,64 all.rc 
      size   ratio     E MB/s   D MB/s function prdid='s(5)'
 404887172  47.11%      25.65     9.31 11:rcmr      o2 8b mixer/sse run         	all.rc
 409985398  47.70%      61.62    62.93 56:ans auto                              	all.rc
 408711108  47.55%      94.23    42.70 64:ans auto  o1 
```

where `all.f16` is the file downloaded from google drive. so, i don't see the same compression ratios that you posted in the forums:
```
> turborc -e11,56,64 all.rc
      size   ratio% bits/value  E MB/s   D MB/s function prdid='s(5)'                  quantization
 197783868  11.51%   1,84        22.63    24.21 11:rcmr      o2 8b mixer/sse run       q6      
 198108780  11.52%   1,84        25.48    26.80  9:rcms      o1 mixer/sse              q6
 199583360  11.61%   1,86       142.01    84.27 64:ans auto  o1                        q6
 200876698  11.69%   1,87       116.35   198.72 56:ans auto                            q6
 216977108  12,63    2,02         0.45    35.00 7-zip / lzma default                   q6
 404605980  23.54%   3,77        22.71    20.15 11:rcmr      o2 8b mixer/sse run       q8
 409701608  23.83%   3,81       111.51   194.99 56:ans auto                            q8
 433717248  25,23    4,04         0.44    34.27 7-zip / lzma default                   q8
```

nor do i see the same output for that command (it seems to have tried more compression strategies than just the 3 specified on the same command line?)

**Comment by powturbo** [comment]
You can see that the sizes are nearly the same as those from the forum.
I've manually changed the compression ratio relative to the original file size (1719042048->859523271), because with the preprocessing we get a smaller file all.rc = 859523271 bytes.

1719042048->859523271 all.f16 -> all.rc
859523271 -> 409701608 all.rc (ans auto)

409701608  * 100 / 1719042048 -> 23,83%

**Comment by powturbo** [comment]
> How do I convert it back into the uncompressed f16 form after all of this? 

simply use the option -d (decompress) to reconvert all.rc to all.
The quantization is lossy and thus irreversible, you'll not get the same "all" file, but an approximate one.

> Also, are the compression schemes you used (11,56,64) all lossless?

Yes, only the preprocessing is lossy
